/*
*     Generated by class-dump 3.1.1.
*
*     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
*/
 
#import <Foundation/Foundation.h>

@interface WebFontCache : NSObject
{
}

+ (struct __GSFont *)createFontWithFamily:(id)fp8 traits:(unsigned int)fp12 size:(float)fp16;
 
@end